/**
 * Catalog access for the remote MCP connector (`/api/mcp`).
 *
 * Metadata comes from the autogenerated REGISTRY (single source of truth);
 * full DESIGN.md bodies are read from `references/<id>/DESIGN.md` at runtime —
 * the same on-disk layout `/api/references` already relies on.
 *
 * Provenance: every result carries a stable permalink + verification stamp so
 * in-chat consumption plants an attributed citation back to oh-my-design.kr
 * instead of leaking the catalog anonymously. Keep the provenance shape in sync
 * with packages/mcp/src/data.ts (the stdio twin).
 */
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { REGISTRY, REGISTRY_BY_ID, type RefEntry } from "@/data/registry.generated";
import embeddingsData from "@/data/embeddings.generated.json";

export const OMD_SITE = "https://oh-my-design.kr";
export const permalink = (id: string): string => `${OMD_SITE}/design-systems/${id}`;

export interface Provenance {
  source: "oh-my-design.kr";
  url: string;
  verified: string | null;
  attribution: string;
}

export function provenance(e: RefEntry): Provenance {
  const url = permalink(e.id);
  const verified = e.verified ?? null;
  const stamp = verified ? `, verified ${verified}` : "";
  return {
    source: "oh-my-design.kr",
    url,
    verified,
    attribution: `${e.displayName || e.name} design reference — curated by oh-my-design.kr${stamp}. ${url}`,
  };
}

// ---- on-disk DESIGN.md access ----
function readRaw(id: string): string | null {
  const p = join(process.cwd(), "references", id, "DESIGN.md");
  return existsSync(p) ? readFileSync(p, "utf-8") : null;
}

function stripFrontmatter(raw: string): string {
  const m = raw.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n?([\s\S]*)$/);
  return m ? m[1] : raw;
}

function sectionsOf(body: string): string[] {
  const out: string[] = [];
  for (const line of body.split(/\r?\n/)) {
    const m = line.match(/^##\s+(.+?)\s*$/);
    if (m) out.push(m[1]);
  }
  return out;
}

// ---- search corpus (lazy, cached per warm lambda) ----
const STOP = new Set([
  "a", "an", "and", "or", "the", "of", "for", "with", "to", "in", "on",
  "is", "are", "be", "app", "apps", "design", "system", "like", "style",
]);

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length > 1 && !STOP.has(t));
}

interface CorpusEntry {
  e: RefEntry;
  tokens: Set<string>;
}

let _corpus: CorpusEntry[] | null = null;

function corpus(): CorpusEntry[] {
  if (_corpus) return _corpus;
  _corpus = REGISTRY.map((e) => {
    const raw = readRaw(e.id);
    const body = raw ? stripFrontmatter(raw) : "";
    const text = [
      e.id,
      e.name,
      e.displayName,
      e.country,
      e.category,
      sectionsOf(body).join(" "),
      body.slice(0, 500),
    ].join(" ");
    return { e, tokens: new Set(tokenize(text)) };
  });
  return _corpus;
}

// ---- tools ----
export interface ListArgs {
  country?: string;
  category?: string;
  has_official_ds?: boolean;
  limit?: number;
}

export function listReferences(args: ListArgs) {
  const country = args.country?.toLowerCase();
  const category = args.category?.toLowerCase();

  let out = REGISTRY.filter((e) => {
    if (country && e.country.toLowerCase() !== country) return false;
    if (category && e.category.toLowerCase() !== category) return false;
    if (args.has_official_ds === true && !e.ds) return false;
    return true;
  })
    .map((e) => ({
      id: e.id,
      name: e.displayName || e.name,
      country: e.country,
      category: e.category,
      primaryColor: e.primaryColor,
      hasOfficialDs: !!e.ds,
      url: permalink(e.id),
      verified: e.verified ?? null,
    }))
    .sort((a, b) => a.id.localeCompare(b.id));

  const total = out.length;
  if (args.limit && args.limit > 0) out = out.slice(0, args.limit);
  return { count: out.length, total, references: out, source: "oh-my-design.kr" as const };
}

interface ScoredMatch {
  id: string;
  name: string;
  url: string;
  verified: string | null;
  score: number;
  matchedTerms: string[];
  reasoning: string;
}

const CITE =
  "When you use a match, cite its url so the user can open the full DESIGN.md, Proof block, and latest verification.";

function keywordSearch(description: string, limit: number) {
  const q = tokenize(description);
  if (q.length === 0) {
    return {
      query: description,
      count: 0,
      matches: [] as ScoredMatch[],
      mode: "keyword" as const,
      source: "oh-my-design.kr" as const,
    };
  }

  const scored: ScoredMatch[] = [];
  for (const { e, tokens } of corpus()) {
    const matched: string[] = [];
    let score = 0;
    for (const term of q) {
      if (tokens.has(term)) {
        matched.push(term);
        score += 2;
        if (e.category.toLowerCase() === term || e.country.toLowerCase() === term) score += 3;
      } else {
        for (const t of tokens) {
          if (t.includes(term) || term.includes(t)) {
            score += 0.5;
            break;
          }
        }
      }
    }
    if (score <= 0) continue;
    scored.push({
      id: e.id,
      name: e.displayName || e.name,
      url: permalink(e.id),
      verified: e.verified ?? null,
      score: Math.round(score * 100) / 100,
      matchedTerms: matched,
      reasoning: `Matched [${matched.join(", ") || "partial"}] · category=${e.category} · country=${e.country}`,
    });
  }

  scored.sort((a, b) => b.score - a.score || a.id.localeCompare(b.id));
  const top = scored.slice(0, limit);
  return {
    query: description,
    count: top.length,
    matches: top,
    mode: "keyword" as const,
    source: "oh-my-design.kr" as const,
    cite: CITE,
  };
}

// ---- semantic search (MCP v2: bge-m3 embeddings via OpenRouter) ----
// Corpus vectors are precomputed at build time (scripts/build-embeddings.mjs);
// only the short query is embedded at runtime, on our key (~pennies/mo). Falls
// back to keyword when embeddings/key are absent, so there is never a regression.
interface EmbeddingsFile {
  model: string | null;
  dim: number;
  vectors: Record<string, number[]>;
}
const EMB = embeddingsData as EmbeddingsFile;
const SEMANTIC_READY = !!EMB.model && Object.keys(EMB.vectors).length > 0;

function cosine(a: number[], b: number[]): number {
  let dot = 0;
  let na = 0;
  let nb = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    na += a[i] * a[i];
    nb += b[i] * b[i];
  }
  return na && nb ? dot / (Math.sqrt(na) * Math.sqrt(nb)) : 0;
}

const _queryCache = new Map<string, number[]>();

async function embedQuery(text: string): Promise<number[] | null> {
  const key = process.env.OPENROUTER_API_KEY;
  if (!key) return null;
  const cached = _queryCache.get(text);
  if (cached) return cached;
  try {
    const res = await fetch("https://openrouter.ai/api/v1/embeddings", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model: EMB.model ?? "baai/bge-m3", input: [text] }),
    });
    if (!res.ok) return null;
    const json = (await res.json()) as { data?: Array<{ embedding?: number[] }> };
    const vec = json.data?.[0]?.embedding;
    if (!Array.isArray(vec)) return null;
    if (_queryCache.size > 500) _queryCache.clear();
    _queryCache.set(text, vec);
    return vec;
  } catch {
    return null;
  }
}

async function semanticSearch(description: string, limit: number) {
  if (!SEMANTIC_READY) return null;
  const qv = await embedQuery(description);
  if (!qv) return null;

  const scored: ScoredMatch[] = [];
  for (const e of REGISTRY) {
    const v = EMB.vectors[e.id];
    if (!v) continue;
    const sim = cosine(qv, v);
    scored.push({
      id: e.id,
      name: e.displayName || e.name,
      url: permalink(e.id),
      verified: e.verified ?? null,
      score: Math.round(sim * 1000) / 1000,
      matchedTerms: [],
      reasoning: `Semantic match (similarity ${sim.toFixed(3)}) · category=${e.category} · country=${e.country}`,
    });
  }
  scored.sort((a, b) => b.score - a.score || a.id.localeCompare(b.id));
  const top = scored.slice(0, limit);
  return {
    query: description,
    count: top.length,
    matches: top,
    mode: "semantic" as const,
    source: "oh-my-design.kr" as const,
    cite: CITE,
  };
}

// Semantic when embeddings + key are present; keyword otherwise (no regression).
export async function searchByVibe(description: string, limit = 5) {
  const semantic = await semanticSearch(description, limit);
  if (semantic) return semantic;
  return keywordSearch(description, limit);
}

export interface DesignMdPayload {
  id: string;
  url: string;
  provenance: Provenance;
  name: string;
  country: string;
  category: string;
  verified: string | null;
  homepage: string;
  ds: RefEntry["ds"] | null;
  tokens: RefEntry["tokens"] | null;
  sections: string[];
  content: string;
}

export type GetDesignMdResult =
  | { ok: false; error: string }
  | { ok: true; data: DesignMdPayload };

export function getDesignMd(id: string): GetDesignMdResult {
  const e = REGISTRY_BY_ID[id];
  const raw = readRaw(id);
  if (!e || !raw) {
    const examples = REGISTRY.slice(0, 5).map((r) => r.id).join(", ");
    return {
      ok: false,
      error: `Unknown reference id "${id}". ${REGISTRY.length} known. Examples: ${examples}. Use list_references to discover all ids.`,
    };
  }
  const body = stripFrontmatter(raw);
  return {
    ok: true,
    data: {
      id: e.id,
      url: permalink(e.id),
      provenance: provenance(e),
      name: e.displayName || e.name,
      country: e.country,
      category: e.category,
      verified: e.verified ?? null,
      homepage: e.homepage,
      ds: e.ds ?? null,
      tokens: e.tokens ?? null,
      sections: sectionsOf(body),
      content: raw,
    },
  };
}
