// AUTO-GENERATED by scripts/wf-curation-profiles.js — do not edit by hand.
// 4-axis curation profiles + supplementary axes for references not in the
// hand-curated REFERENCE_PROFILES. Regenerate when many refs are added.
import type { Temperature, Density, Elevation, Shape } from "./types";

export const GENERATED_PROFILES: Record<string, { t: Temperature; d: Density; e: Elevation; s: Shape }> = {
  "17live": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "29cm": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "91app": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "ably": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "alipay": {
    "t": "C",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "appier": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "S"
  },
  "banksalad": {
    "t": "C",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "bilibili": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "bithumb": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "bunjang": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "cakeresume": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "catchtable": {
    "t": "W",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "channeltalk": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "class101": {
    "t": "W",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "classting": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "classum": {
    "t": "W",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "coinone": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "cookpad": {
    "t": "W",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "coupang": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "dabang": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "devsisters": {
    "t": "W",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "dji": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "drnow": {
    "t": "W",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "fastcampus": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "flex": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "flo": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "S"
  },
  "fugle": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "gangnamunni": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "gmarket": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "gogolook": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "gogoro": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "grip": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "hahow": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "hogangnono": {
    "t": "C",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "hyundaicard": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "ichef": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "inflearn": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "jkopay": {
    "t": "W",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "jobkorea": {
    "t": "C",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "jumpit": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "kakaobank": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "kakaopay": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "kakaot": {
    "t": "W",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "kbank": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "kdan": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "kkbox": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "kkday": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "krafton": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "krds": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "kream": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "kurly": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "S"
  },
  "laftel": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "S"
  },
  "lezhin": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "lunit": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "meituan": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "melon": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "millie": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "momoshop": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "money-forward": {
    "t": "C",
    "d": "D",
    "e": "L",
    "s": "S"
  },
  "musinsa": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "mustit": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "myrealtrip": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "naver": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "naverwebtoon": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "nhncloud": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "note": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "ohouse": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "oliveyoung": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "payco": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "piccollage": {
    "t": "W",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "publy": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "qanda": {
    "t": "W",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "rayark": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "remember": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "ridi": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "riiid": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "sendbird": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "smarthr": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "smartnews": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "socar": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "spoon": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "tada": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "toss-securities": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "tossbank": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "trenbe": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "triple": {
    "t": "C",
    "d": "O",
    "e": "L",
    "s": "R"
  },
  "tumblbug": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "tving": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "upbit": {
    "t": "C",
    "d": "D",
    "e": "F",
    "s": "S"
  },
  "upstage": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "velog": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "voicetube": {
    "t": "W",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "wadiz": {
    "t": "C",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "wanted": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "watcha": {
    "t": "W",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "wavve": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "wconcept": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "xiaohongshu": {
    "t": "W",
    "d": "D",
    "e": "F",
    "s": "R"
  },
  "yanolja": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "yeogiotte": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "R"
  },
  "yogiyo": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  },
  "zigbang": {
    "t": "C",
    "d": "O",
    "e": "F",
    "s": "S"
  },
  "zigzag": {
    "t": "W",
    "d": "D",
    "e": "L",
    "s": "R"
  }
};

export const GENERATED_SUPPLEMENTARY: Record<string, { saturation: "muted" | "vivid"; typography: "geometric" | "humanist" | "monospace"; darkNative: boolean }> = {
  "17live": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": true
  },
  "29cm": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "91app": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "ably": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "alipay": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "appier": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "banksalad": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "bilibili": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "bithumb": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": true
  },
  "bunjang": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "cakeresume": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "catchtable": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "channeltalk": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "class101": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "classting": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "classum": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "coinone": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": false
  },
  "cookpad": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "coupang": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "dabang": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": false
  },
  "devsisters": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "dji": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": true
  },
  "drnow": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "fastcampus": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "flex": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "flo": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "fugle": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "gangnamunni": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "gmarket": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "gogolook": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "gogoro": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": true
  },
  "grip": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": true
  },
  "hahow": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "hogangnono": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "hyundaicard": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "ichef": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "inflearn": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "jkopay": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "jobkorea": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "jumpit": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "kakaobank": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "kakaopay": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "kakaot": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "kbank": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "kdan": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "kkbox": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": true
  },
  "kkday": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "krafton": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": true
  },
  "krds": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": false
  },
  "kream": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": false
  },
  "kurly": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "laftel": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": true
  },
  "lezhin": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": true
  },
  "lunit": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": false
  },
  "meituan": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "melon": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "millie": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "momoshop": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "money-forward": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "musinsa": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "mustit": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "myrealtrip": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "naver": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "naverwebtoon": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "nhncloud": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "note": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "ohouse": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "oliveyoung": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": false
  },
  "payco": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "piccollage": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "publy": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "qanda": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "rayark": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": true
  },
  "remember": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "ridi": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "riiid": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "sendbird": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "smarthr": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "smartnews": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "socar": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "spoon": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "tada": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "toss-securities": {
    "saturation": "muted",
    "typography": "geometric",
    "darkNative": true
  },
  "tossbank": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "trenbe": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "triple": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "tumblbug": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "tving": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": true
  },
  "upbit": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "upstage": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": true
  },
  "velog": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "voicetube": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": true
  },
  "wadiz": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "wanted": {
    "saturation": "vivid",
    "typography": "geometric",
    "darkNative": false
  },
  "watcha": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": true
  },
  "wavve": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": true
  },
  "wconcept": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "xiaohongshu": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "yanolja": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "yeogiotte": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "yogiyo": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  },
  "zigbang": {
    "saturation": "muted",
    "typography": "humanist",
    "darkNative": false
  },
  "zigzag": {
    "saturation": "vivid",
    "typography": "humanist",
    "darkNative": false
  }
};
