/**
 * Curated reference collections — /collections/[slug] (#5).
 *
 * Intent-keyword pSEO surfaces (the Refero collection pattern): each slug
 * targets a search/launch-post phrase and selects references from the
 * autogenerated registry — category/country filters where the frontmatter
 * supports it, explicit id allowlists where the intent is editorial
 * (claude-code / cursor starter packs), and a token-derived luminance check
 * for dark-mode. No hand-maintained per-collection reference lists to drift.
 *
 * Every collection must yield ≥6 references — verified by the vitest-less
 * invariant check in getCollectionEntries (throws at build time inside
 * generateStaticParams if a filter goes thin after a registry change).
 */

import { REGISTRY, REGISTRY_BY_ID, type RefEntry } from "@/data/registry.generated";
import type { DesignSystemInfo } from "@/lib/design-systems";

export interface Collection {
  slug: string;
  /** H1 / link label */
  titleKr: string;
  titleEn: string;
  /** Two short intro paragraphs each — KR first (Korean-first site), EN after. */
  introKr: [string, string];
  introEn: [string, string];
  select: (registry: readonly RefEntry[]) => RefEntry[];
  /** Slugs shown in the "related collections" block. */
  related: [string, string, string];
}

const byIds = (ids: string[]) => () =>
  ids.map((id) => REGISTRY_BY_ID[id]).filter(Boolean) as RefEntry[];

const byCountryCategory =
  (countries: string[] | null, categories: string[] | null) =>
  (registry: readonly RefEntry[]) =>
    registry.filter(
      (e) =>
        (!countries || countries.includes(e.country)) &&
        (!categories || categories.includes(e.category)),
    );

/** Dark-mode-native detection: registry token canvas/background luminance. */
function isDarkCanvas(e: RefEntry): boolean {
  const colors = e.tokens?.colors ?? e.tokens?.color;
  const hex = colors?.["canvas"] ?? colors?.["background"];
  if (!hex || !/^#[0-9a-fA-F]{6}$/.test(hex)) return false;
  const n = parseInt(hex.slice(1), 16);
  const lum =
    (0.299 * (n >> 16) + 0.587 * ((n >> 8) & 255) + 0.114 * (n & 255)) / 255;
  return lum < 0.25;
}

export const COLLECTIONS: readonly Collection[] = [
  {
    slug: "claude-code-design-md",
    titleKr: "Claude Code용 DESIGN.md 스타터 팩",
    titleEn: "DESIGN.md for Claude Code",
    introKr: [
      "Claude Code는 코드를 잘 짜지만, 디자인 취향은 남의 것입니다. DESIGN.md 한 파일을 프로젝트에 두면 에이전트가 매 UI 작업 전에 브랜드의 색·타이포·보이스를 ground truth로 읽습니다.",
      "이 컬렉션은 Claude Code 사용자들이 가장 먼저 적용해 보는 검증된 레퍼런스 모음입니다. 카드를 열어 DESIGN.md를 그대로 복사하거나, 한 줄 설치로 221개 전부를 스킬과 함께 들여올 수 있습니다.",
    ],
    introEn: [
      "Claude Code ships beautiful code with someone else's design taste. Drop one DESIGN.md in your project and the agent reads your brand's color, type, and voice as ground truth before every UI task.",
      "These are the verified references Claude Code users reach for first. Open a card to copy the DESIGN.md raw, or install all 221 with skills in one command.",
    ],
    select: byIds([
      "toss",
      "stripe",
      "linear.app",
      "vercel",
      "notion",
      "raycast",
      "supabase",
      "figma",
      "github",
      "cursor",
      "openai",
      "perplexity",
    ]),
    related: ["cursor-design-md", "dev-tools", "clean-saas"],
  },
  {
    slug: "cursor-design-md",
    titleKr: "Cursor용 DESIGN.md 스타터 팩",
    titleEn: "DESIGN.md for Cursor",
    introKr: [
      "Cursor 룰에 디자인 토큰 몇 줄을 흩뿌리는 대신, 브랜드 전체를 담은 DESIGN.md 하나를 .cursor/rules로 연결하세요. 색상 헥스부터 금지 카피까지 한 파일이 단일 소스가 됩니다.",
      "Cursor 사용자에게 잘 맞는 레퍼런스를 모았습니다 — 개발 도구·SaaS 중심의 깔끔한 시스템들. 설치는 한 줄, 이후엔 자연어로 요청하면 됩니다.",
    ],
    introEn: [
      "Instead of scattering a few design tokens across Cursor rules, wire one DESIGN.md carrying the whole brand into .cursor/rules. From color hexes to forbidden copy, one file is the single source.",
      "A pick of references that fit Cursor workflows — clean dev-tool and SaaS systems. One-line install, then just ask in natural language.",
    ],
    select: byIds([
      "cursor",
      "vercel",
      "linear.app",
      "framer",
      "resend",
      "mercury",
      "sentry",
      "posthog",
      "mintlify",
      "cal",
      "stripe",
      "figma",
    ]),
    related: ["claude-code-design-md", "dev-tools", "dark-mode"],
  },
  {
    slug: "korean-fintech",
    titleKr: "한국 핀테크 디자인 시스템",
    titleEn: "Korean Fintech Design Systems",
    introKr: [
      "토스가 바꿔 놓은 한국 핀테크 UI — 큰 타이포, 한 화면 한 행동, 금융 용어 없는 카피. 토스·카카오뱅크·뱅크샐러드·업비트까지, 실서비스에서 라이브 추출·검증한 DESIGN.md로 모았습니다.",
      "각 문서는 색·타이포 토큰뿐 아니라 보이스와 금지 표현까지 담습니다. 핀테크 제품을 만드는 에이전트에게 그대로 먹이세요.",
    ],
    introEn: [
      "Korean fintech UI after Toss: big type, one action per screen, copy without banking jargon. Toss, KakaoBank, Banksalad, Upbit — every DESIGN.md live-extracted and verified from the production service.",
      "Each file carries voice and forbidden phrases, not just color and type tokens. Feed it straight to the agent building your fintech product.",
    ],
    select: byCountryCategory(["KR"], ["fintech", "finance"]),
    related: ["korean-apps", "clean-saas", "claude-code-design-md"],
  },
  {
    slug: "korean-apps",
    titleKr: "한국 앱 디자인 시스템",
    titleEn: "Korean App Design Systems",
    introKr: [
      "당근·배민·29CM·무신사 — 한국 소비자 앱의 디자인 언어는 영어권 레퍼런스로는 절대 안 나옵니다. 한국 시장의 밀도와 톤을 담은 검증된 DESIGN.md 모음입니다.",
      "커머스·커뮤니티·콘텐츠·교육까지, 국내 주요 서비스의 실제 토큰과 컴포넌트 패턴을 라이브 추출했습니다. 한국 사용자 대상 제품이라면 여기서 시작하세요.",
    ],
    introEn: [
      "Karrot, Baemin, 29CM, Musinsa — the design language of Korean consumer apps never falls out of English-market references. Verified DESIGN.md files carrying the density and tone of the Korean market.",
      "Commerce, community, content, education: real tokens and component patterns live-extracted from Korea's major services. Building for Korean users? Start here.",
    ],
    select: byCountryCategory(
      ["KR"],
      [
        "consumer-tech",
        "ecommerce",
        "e-commerce",
        "entertainment",
        "travel",
        "local-services",
        "audio-social",
      ],
    ),
    related: ["korean-fintech", "japanese-brands", "dark-mode"],
  },
  {
    slug: "japanese-brands",
    titleKr: "일본 브랜드 디자인 시스템",
    titleEn: "Japanese Brand Design Systems",
    introKr: [
      "LINE·메루카리·쿡패드·freee·SmartHR — 일본 디지털 프로덕트 특유의 절제와 친절함을 담은 레퍼런스 모음입니다. 일본어 타이포그래피 운용까지 실서비스에서 검증했습니다.",
      "일본 시장용 제품을 만들거나, JP 톤의 차분한 UI가 필요할 때 에이전트에게 그대로 전달하세요.",
    ],
    introEn: [
      "LINE, Mercari, Cookpad, freee, SmartHR — references carrying the restraint and politeness specific to Japanese digital products, including how they actually run Japanese typography in production.",
      "Building for the Japanese market, or just need that calm JP tone? Hand these to your agent as-is.",
    ],
    select: byCountryCategory(["JP"], null),
    related: ["korean-apps", "clean-saas", "claude-code-design-md"],
  },
  {
    slug: "dev-tools",
    titleKr: "개발자 도구 디자인 시스템",
    titleEn: "Developer Tool Design Systems",
    introKr: [
      "GitHub·Sentry·MongoDB·ClickHouse — 개발자 도구의 UI는 정보 밀도와 신뢰가 전부입니다. 모노스페이스 운용, 코드 블록, 대시보드 패턴까지 검증한 DESIGN.md를 모았습니다.",
      "데브툴·인프라 제품을 만든다면 이 톤에서 시작하는 것이 가장 빠릅니다.",
    ],
    introEn: [
      "GitHub, Sentry, MongoDB, ClickHouse — dev-tool UI is information density and trust. DESIGN.md files verified down to monospace usage, code blocks, and dashboard patterns.",
      "Building developer or infra products? Starting from this tone is the shortest path.",
    ],
    select: byCountryCategory(null, ["developer-tools", "backend-devops"]),
    related: ["dark-mode", "cursor-design-md", "clean-saas"],
  },
  {
    slug: "clean-saas",
    titleKr: "클린 SaaS 디자인 시스템",
    titleEn: "Clean SaaS Design Systems",
    introKr: [
      "Notion·Slack·Airtable류의 SaaS 디자인 — 여백, 위계, 절제된 색 운용이 핵심입니다. 생산성·SaaS 카테고리에서 검증된 레퍼런스를 모았습니다.",
      "B2B 대시보드나 협업 도구를 만들 때, '깔끔하게'라는 모호한 요청 대신 이 컬렉션의 DESIGN.md 하나를 지정하세요.",
    ],
    introEn: [
      "SaaS design in the Notion / Slack / Airtable family — whitespace, hierarchy, restrained color. Verified references across the productivity and SaaS categories.",
      "Building a B2B dashboard or collaboration tool? Point your agent at one DESIGN.md here instead of saying \"make it clean\".",
    ],
    select: byCountryCategory(null, ["saas", "productivity"]),
    related: ["dev-tools", "claude-code-design-md", "korean-fintech"],
  },
  {
    slug: "dark-mode",
    titleKr: "다크 모드 네이티브 디자인 시스템",
    titleEn: "Dark-Mode-Native Design Systems",
    introKr: [
      "Linear·Vercel·Supabase·Raycast — 다크를 '반전'이 아니라 기본 캔버스로 설계한 브랜드들입니다. 레지스트리 토큰의 캔버스 휘도로 자동 선별했습니다.",
      "다크 UI는 회색 단계와 글로우 운용이 전부입니다. 어설픈 #000 배경 대신, 검증된 다크 팔레트를 에이전트에게 주세요.",
    ],
    introEn: [
      "Linear, Vercel, Supabase, Raycast — brands that design dark as the default canvas, not an inversion. Auto-selected by canvas luminance from the registry tokens.",
      "Dark UI is all gray scales and glow discipline. Give your agent a verified dark palette instead of a naive #000 background.",
    ],
    select: (registry) => registry.filter(isDarkCanvas),
    related: ["dev-tools", "cursor-design-md", "korean-apps"],
  },
];

export const COLLECTIONS_BY_SLUG: Readonly<Record<string, Collection>> =
  Object.freeze(Object.fromEntries(COLLECTIONS.map((c) => [c.slug, c])));

/** Resolve a collection's entries; throws if a filter went thin (<6). */
export function getCollectionEntries(slug: string): RefEntry[] {
  const c = COLLECTIONS_BY_SLUG[slug];
  if (!c) return [];
  const entries = c.select(REGISTRY);
  if (entries.length < 6) {
    throw new Error(
      `collection "${slug}" yields only ${entries.length} references (<6) — adjust its filter in lib/collections.ts`,
    );
  }
  return entries;
}

/** Adapt a registry entry to the DSCard shape — ds-block fields when present,
 *  honest registry-derived fallbacks otherwise (homepage, brand type). */
export function toCardInfo(e: RefEntry): DesignSystemInfo {
  if (e.ds) {
    return {
      refId: e.id,
      name: e.ds.name,
      url: e.ds.url,
      type: e.ds.type,
      description: e.ds.description,
      ogImage: e.ds.ogImage,
    };
  }
  const name = e.displayName || e.name;
  return {
    refId: e.id,
    name,
    url: e.homepage,
    type: "brand",
    description: `${name} — verified DESIGN.md reference (${e.category.replace(/-/g, " ")}, ${e.country}).`,
  };
}
