/**
 * Official design-system / brand-guideline links per reference.
 * Derived from the autogenerated registry — to add or update an entry,
 * edit references/<id>/DESIGN.md frontmatter `ds` block, then run
 * `npm run build-registry`.
 */
import { REGISTRY, REGISTRY_BY_ID } from "@/data/registry.generated";
import {
  REFERENCE_QUALITY_BY_ID,
  type ReferenceQualityStatus,
} from "@/data/reference-quality.generated";

export type DesignSystemType = "system" | "brand" | "reference";

export interface DesignSystemInfo {
  refId: string;
  name: string;
  url: string;
  type: DesignSystemType;
  description: string;
  qualityStatus: ReferenceQualityStatus;
  verifiedAt: string | null;
  /** og:image / twitter:image harvested from the site (scripts/fetch-og-images.mjs).
   *  Missing when the site doesn't publish one — UI falls back to a logo thumbnail. */
  ogImage?: string;
}

export function getDesignSystem(refId: string): DesignSystemInfo | null {
  const e = REGISTRY_BY_ID[refId];
  if (!e?.ds) return null;
  const quality = REFERENCE_QUALITY_BY_ID[refId];
  if (!quality) return null;
  return {
    refId,
    name: e.ds.name,
    url: e.ds.url,
    type: e.ds.type,
    description: e.ds.description,
    ogImage: e.ds.ogImage,
    qualityStatus: quality.status,
    verifiedAt: quality.verifiedAt,
  };
}

export interface RelatedRef {
  id: string;
  name: string;
  category: string;
  primaryColor: string;
}

function hexToRgb(hex: string): [number, number, number] | null {
  const m = hex.replace("#", "").match(/.{2}/g);
  if (!m || m.length < 3) return null;
  return [parseInt(m[0], 16), parseInt(m[1], 16), parseInt(m[2], 16)];
}

/**
 * Sibling references for the detail-page "Related design systems" block.
 * Same category first (the strongest "you might also like" signal), then
 * nearest by primary-color distance, so the list is always full and visually
 * coherent. Deterministic (id tie-break) so SSG output is stable. Powers
 * detail→detail internal links for session + crawl depth.
 */
export function getRelatedReferences(id: string, n = 6): RelatedRef[] {
  const self = REGISTRY_BY_ID[id];
  if (!self) return [];
  const selfRgb = hexToRgb(self.primaryColor);

  const scored = REGISTRY.filter((e) => e.id !== id).map((e) => {
    const sameCat = e.category === self.category ? 0 : 1;
    const rgb = hexToRgb(e.primaryColor);
    const dist =
      selfRgb && rgb
        ? Math.sqrt(
            (selfRgb[0] - rgb[0]) ** 2 +
              (selfRgb[1] - rgb[1]) ** 2 +
              (selfRgb[2] - rgb[2]) ** 2,
          )
        : Number.MAX_SAFE_INTEGER;
    return { e, sameCat, dist };
  });

  scored.sort(
    (a, b) => a.sameCat - b.sameCat || a.dist - b.dist || a.e.id.localeCompare(b.e.id),
  );

  return scored.slice(0, n).map(({ e }) => ({
    id: e.id,
    name: e.displayName || e.name,
    category: e.category,
    primaryColor: e.primaryColor,
  }));
}

/** All 400 references; official systems first, then brand guides, then refs. */
export function getAllDesignSystems(): DesignSystemInfo[] {
  return REGISTRY
    .map<DesignSystemInfo>(e => {
      const quality = REFERENCE_QUALITY_BY_ID[e.id];
      if (!quality) throw new Error(`reference quality missing for ${e.id}`);
      const name = e.displayName || e.name;
      return {
        refId: e.id,
        name: e.ds?.name ?? name,
        url: e.ds?.url ?? e.homepage,
        type: (e.ds?.type ?? "reference") as DesignSystemType,
        description: e.ds?.description
          ?? `${name} DESIGN.md reference · ${e.category.replace(/-/g, " ")} · ${e.country}`,
        ogImage: e.ds?.ogImage,
        qualityStatus: quality.status,
        verifiedAt: quality.verifiedAt,
      };
    })
    .sort((a, b) => {
      const order: Record<DesignSystemType, number> = { system: 0, brand: 1, reference: 2 };
      if (a.type !== b.type) return order[a.type] - order[b.type];
      return a.name.localeCompare(b.name);
    });
}
