/**
 * Official design-system / brand-guideline links per reference.
 * Derived from the autogenerated registry — to add or update an entry,
 * edit references/<id>/DESIGN.md frontmatter `ds` block, then run
 * `npm run build-registry`.
 */
import { REGISTRY, REGISTRY_BY_ID } from "@/data/registry.generated";

export type DesignSystemType = "system" | "brand";

export interface DesignSystemInfo {
  refId: string;
  name: string;
  url: string;
  type: DesignSystemType;
  description: string;
  /** og:image / twitter:image harvested from the site (scripts/fetch-og-images.mjs).
   *  Missing when the site doesn't publish one — UI falls back to a logo thumbnail. */
  ogImage?: string;
}

export function getDesignSystem(refId: string): DesignSystemInfo | null {
  const e = REGISTRY_BY_ID[refId];
  if (!e?.ds) return null;
  return {
    refId,
    name: e.ds.name,
    url: e.ds.url,
    type: e.ds.type,
    description: e.ds.description,
    ogImage: e.ds.ogImage,
  };
}

/** All design-system entries, full systems first (alphabetical within each type). */
export function getAllDesignSystems(): DesignSystemInfo[] {
  return REGISTRY
    .filter(e => e.ds)
    .map(e => ({
      refId: e.id,
      name: e.ds!.name,
      url: e.ds!.url,
      type: e.ds!.type,
      description: e.ds!.description,
      ogImage: e.ds!.ogImage,
    }))
    .sort((a, b) => {
      if (a.type !== b.type) return a.type === "system" ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
}
