/** Main homepage URL for each reference — distinct from the DS/brand-guidelines URL. */
export const HOMEPAGE_URLS: Record<string, string> = {
  airbnb:        "https://www.airbnb.com",
  airtable:      "https://www.airtable.com",
  apple:         "https://www.apple.com",
  baemin:        "https://www.baemin.com",
  bmw:           "https://www.bmw.com",
  cal:           "https://cal.com",
  claude:        "https://claude.ai",
  clay:          "https://www.clay.com",
  clickhouse:    "https://clickhouse.com",
  cohere:        "https://cohere.com",
  coinbase:      "https://www.coinbase.com",
  composio:      "https://composio.dev",
  cursor:        "https://www.cursor.com",
  dcard:         "https://www.dcard.tw",
  elevenlabs:    "https://elevenlabs.io",
  expo:          "https://expo.dev",
  ferrari:       "https://www.ferrari.com",
  figma:         "https://www.figma.com",
  framer:        "https://www.framer.com",
  freee:         "https://www.freee.co.jp",
  hashicorp:     "https://www.hashicorp.com",
  ibm:           "https://www.ibm.com",
  intercom:      "https://www.intercom.com",
  kakao:         "https://www.kakao.com",
  karrot:        "https://www.karrotmarket.com",
  kraken:        "https://www.kraken.com",
  lamborghini:   "https://www.lamborghini.com",
  line:          "https://line.me",
  "linear.app":  "https://linear.app",
  lovable:       "https://lovable.dev",
  mercari:       "https://www.mercari.com",
  minimax:       "https://www.minimaxi.com",
  mintlify:      "https://mintlify.com",
  miro:          "https://miro.com",
  "mistral.ai":  "https://mistral.ai",
  mongodb:       "https://www.mongodb.com",
  notion:        "https://www.notion.so",
  nvidia:        "https://www.nvidia.com",
  ollama:        "https://ollama.com",
  "opencode.ai": "https://opencode.ai",
  pinkoi:        "https://www.pinkoi.com",
  pinterest:     "https://www.pinterest.com",
  posthog:       "https://posthog.com",
  raycast:       "https://www.raycast.com",
  renault:       "https://www.renault.com",
  replicate:     "https://replicate.com",
  resend:        "https://resend.com",
  revolut:       "https://www.revolut.com",
  runwayml:      "https://runwayml.com",
  sanity:        "https://www.sanity.io",
  sentry:        "https://sentry.io",
  spacex:        "https://www.spacex.com",
  spotify:       "https://www.spotify.com",
  stripe:        "https://stripe.com",
  supabase:      "https://supabase.com",
  superhuman:    "https://superhuman.com",
  tesla:         "https://www.tesla.com",
  "together.ai": "https://www.together.ai",
  toss:          "https://toss.im",
  uber:          "https://www.uber.com",
  vercel:        "https://vercel.com",
  voltagent:     "https://voltagent.dev",
  warp:          "https://www.warp.dev",
  webflow:       "https://webflow.com",
  wise:          "https://wise.com",
  "x.ai":        "https://x.ai",
  zapier:        "https://zapier.com",
};

export function getHomepageUrl(refId: string): string | null {
  return HOMEPAGE_URLS[refId] ?? null;
}
