// Logo helpers — derived from the autogenerated registry. SERVER-SIDE ONLY in
// practice: importing this from a "use client" module bundles the whole 2 MB
// registry into that route (see client-registry-boundary.test.ts). Client
// components take a LogoRef prop and use the pure helpers in ./logo-urls.
// Source of truth: references/<id>/DESIGN.md frontmatter `logo` + `homepage`.

import { REGISTRY_BY_ID } from "@/data/registry.generated";
import { isRasterLogo, logoFallbackUrl, logoUrl, type LogoRef } from "./logo-urls";

export type { LogoRef } from "./logo-urls";

/** The serializable logo descriptor a client component needs for `id`. */
export function getLogoRef(id: string): LogoRef | null {
  const entry = REGISTRY_BY_ID[id];
  if (!entry) return null;
  return { id, type: entry.logo.type, slug: entry.logo.slug, homepage: entry.homepage };
}

export function getLogoUrl(id: string, color?: string): string | null {
  return logoUrl(getLogoRef(id), color);
}

/** Best-guess fallback favicon — Google's proxy, derived from the homepage host. */
export function getLogoFallbackUrl(id: string): string | null {
  return logoFallbackUrl(getLogoRef(id));
}

/** Treat github + favicon logos as needing the fallback mShots/proxy path. */
export function isGitHubLogo(id: string): boolean {
  return isRasterLogo(getLogoRef(id));
}
