// Logo helpers — derived from the autogenerated registry.
// Source of truth: references/<id>/DESIGN.md frontmatter `logo` + `homepage`.
//
// 1. Simple Icons CDN (SVG, supports color): https://cdn.simpleicons.org/{slug}/{color}
// 2. GitHub org avatars (PNG, always works):  https://github.com/{org}.png?size=64
// 3. Favicon: direct URL stored in slug (preferred), or Google's favicon proxy fallback.

import { REGISTRY_BY_ID } from "@/data/registry.generated";

export function getLogoUrl(id: string, color?: string): string | null {
  const entry = REGISTRY_BY_ID[id];
  if (!entry) return null;
  const { type, slug } = entry.logo;

  if (type === "github") return `https://github.com/${slug}.png?size=64`;
  if (type === "favicon") return slug;
  // simpleicons
  const c = color ? color.replace("#", "") : "white";
  return `https://cdn.simpleicons.org/${slug}/${c}`;
}

/** Best-guess fallback favicon — Google's proxy, derived from the homepage host. */
export function getLogoFallbackUrl(id: string): string | null {
  const entry = REGISTRY_BY_ID[id];
  if (!entry) return null;
  let domain: string;
  try {
    domain = new URL(entry.homepage).hostname.replace(/^www\./, "");
  } catch {
    domain = `${id}.com`;
  }
  return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=64`;
}

/** Treat github + favicon logos as needing the fallback mShots/proxy path. */
export function isGitHubLogo(id: string): boolean {
  const t = REGISTRY_BY_ID[id]?.logo.type;
  return t === "github" || t === "favicon";
}
