// AUTO-GENERATED by scripts/build-registry.mjs — bundled skill + sub-agent counts.
// SKILL_COUNT = package.json "files" entries under skills/ (what npm ships).
// SUBAGENT_COUNT = agents/omd-*.md (mirrors install-skills.ts's agent filter).
// REFERENCE_COUNT = REGISTRY.length, emitted as a literal so client components can
// print the count without bundling the 2 MB registry.
export const REFERENCE_COUNT = 521;
export const SKILL_COUNT = 28;
export const SUBAGENT_COUNT = 20;
