// AUTO-GENERATED by scripts/build-registry.mjs — bundled skill + sub-agent counts.
// SKILL_COUNT = package.json "files" entries under skills/ (what npm ships).
// SUBAGENT_COUNT = agents/omd-*.md (mirrors install-skills.ts's agent filter).
export const SKILL_COUNT = 18;
export const SUBAGENT_COUNT = 16;
