/**
 * Font Playground — curated catalog (60 fonts · 40 Hangul + 20 Latin).
 *
 * Freely-usable fonts pulled from Google Fonts (css2 CDN) plus noonnu
 * favorites served through jsdelivr / webfontworld when not on Google.
 * The playground curates and points at the source — it does not host or
 * redistribute font files — so every entry just needs a free-commercial-
 * use license, not specifically OFL. Render via the shell's single
 * consolidated Google `<link>` + per-jsdelivr `<style>`.
 *
 * Tag quality is what makes reference-based discovery work — mood / era /
 * use / personality tags should be hand-curated, not scraped.
 */

import type { FontEntry } from "./types";

const SAMPLE = {
  latin: "Design is intelligence made visible",
  hangul: "디자인은 보이는 지성이다",
} as const;

export const FONT_CATALOG: FontEntry[] = [
  /* ─────────── Korean (6) ─────────── */
  {
    id: "pretendard",
    name: "Pretendard",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Pretendard", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 500 }],
    license: "OFL-1.1",
    source: "https://github.com/orioncactus/pretendard",
    description:
      "System-grade Korean + Latin unified sans. Shipped by Kil Hyungjin as a remix of Source Han Sans + Inter.",
    loader: { kind: "google", family: "Pretendard:wght@100..900" },
    tags: {
      mood: ["clean", "modern", "neutral"],
      era: ["2020s"],
      use: ["ui", "body", "display"],
      personality: ["professional", "approachable", "universal"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "Kil Hyungjin",
  },
  {
    id: "noto-sans-kr",
    name: "Noto Sans KR",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Noto Sans KR", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/noto/specimen/Noto+Sans+KR",
    description:
      "Google's universal Korean sans. Unmatched script coverage (11,172 Hangul + CJK). Reads neutrally, ships everywhere.",
    loader: { kind: "google", family: "Noto+Sans+KR:wght@100..900" },
    tags: {
      mood: ["neutral", "technical"],
      era: ["2020s"],
      use: ["body", "ui", "heading"],
      personality: ["professional", "universal", "safe"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "Adobe + Google",
  },
  {
    id: "gowun-dodum",
    name: "Gowun Dodum",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gowun Dodum", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Gowun+Dodum",
    description:
      "Gentle, slightly rounded Korean sans. Humanist terminals. Feels conversational — good for warm product copy.",
    loader: { kind: "google", family: "Gowun+Dodum" },
    tags: {
      mood: ["warm", "friendly", "soft"],
      era: ["contemporary"],
      use: ["body", "ui", "display"],
      personality: ["approachable", "humanist", "gentle"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "Gowun Batang",
  },
  {
    id: "jua",
    name: "Jua",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Jua", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Jua",
    description:
      "Woowa Brothers' 주아체 — chunky, playful, handwritten feel. Iconic on Korean delivery / casual surfaces.",
    loader: { kind: "google", family: "Jua" },
    tags: {
      mood: ["playful", "warm", "bold"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["friendly", "quirky", "confident"],
    },
    sampleText: {
      latin: "Sell what you don't need",
      hangul: "치킨은 살 안 쪄요",
    },
    designer: "Woowa Brothers (우아한형제들)",
  },
  {
    id: "nanum-pen-script",
    name: "Nanum Pen Script",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Nanum Pen Script", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Nanum+Pen+Script",
    description:
      "Naver's ballpoint-pen script. Intimate, hurried, unpolished — the opposite of corporate chrome.",
    loader: { kind: "google", family: "Nanum+Pen+Script" },
    tags: {
      mood: ["handwritten", "casual", "personal"],
      era: ["timeless"],
      use: ["display", "accent", "annotation"],
      personality: ["personal", "relaxed", "authentic"],
    },
    sampleText: {
      latin: "Handwritten notes feel closer",
      hangul: "손으로 쓴 글은 가깝게 느껴져요",
    },
    designer: "Naver",
  },
  {
    id: "black-han-sans",
    name: "Black Han Sans",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Black Han Sans", sans-serif`,
    variable: false,
    axes: [],
    weights: [900],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Black+Han+Sans",
    description:
      "Heavy Korean display sans — pure poster weight. Immediate shout-at-you presence for headlines.",
    loader: { kind: "google", family: "Black+Han+Sans" },
    tags: {
      mood: ["bold", "impactful", "assertive"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["confident", "strong", "loud"],
    },
    sampleText: {
      latin: "Make it bold",
      hangul: "확실하게 주장한다",
    },
    designer: "Zess Type",
  },

  /* ─────────── Latin sans (4) ─────────── */
  {
    id: "inter",
    name: "Inter",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Inter", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 400 }],
    license: "OFL-1.1",
    source: "https://github.com/rsms/inter",
    description:
      "The default UI sans of the 2020s. Optimized for small-text legibility on screens. If in doubt, this.",
    loader: { kind: "google", family: "Inter:wght@100..900" },
    tags: {
      mood: ["clean", "neutral", "technical"],
      era: ["2010s", "2020s"],
      use: ["ui", "body"],
      personality: ["professional", "humanist", "pragmatic"],
    },
    sampleText: { latin: SAMPLE.latin },
    designer: "Rasmus Andersson",
  },
  {
    id: "geist",
    name: "Geist",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Geist", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 400 }],
    license: "OFL-1.1",
    source: "https://vercel.com/font",
    description:
      "Vercel's in-house sans. Sharper than Inter, engineered for interface chrome that looks considered.",
    loader: { kind: "google", family: "Geist:wght@100..900" },
    tags: {
      mood: ["sharp", "technical", "clean"],
      era: ["2020s"],
      use: ["ui", "display", "heading"],
      personality: ["professional", "precise", "modern"],
    },
    sampleText: { latin: SAMPLE.latin },
    designer: "Vercel + Basement.Studio",
  },
  {
    id: "manrope",
    name: "Manrope",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Manrope", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 200, max: 800, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Manrope",
    description:
      "Friendly, semi-geometric sans. Softer than Inter, warmer than Geist — a common sweet spot for landing-page body.",
    loader: { kind: "google", family: "Manrope:wght@200..800" },
    tags: {
      mood: ["friendly", "modern", "warm"],
      era: ["2020s"],
      use: ["ui", "body", "heading"],
      personality: ["approachable", "humanist", "balanced"],
    },
    sampleText: { latin: SAMPLE.latin },
    designer: "Mikhail Sharanda",
  },
  {
    id: "recursive",
    name: "Recursive",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Recursive", sans-serif`,
    variable: true,
    axes: [
      { tag: "MONO", name: "Monospace", min: 0, max: 1, default: 0 },
      { tag: "CASL", name: "Casual", min: 0, max: 1, default: 0 },
      { tag: "wght", name: "Weight", min: 300, max: 1000, default: 400 },
      { tag: "slnt", name: "Slant", min: -15, max: 0, default: 0 },
      { tag: "CRSV", name: "Cursive", min: 0, max: 1, default: 0.5 },
    ],
    license: "OFL-1.1",
    source: "https://www.recursive.design/",
    description:
      "Five-axis variable. Move from precise sans → casual humanist → full monospace on the same family. Maximum expressiveness per KB.",
    loader: {
      kind: "google",
      family: "Recursive:CASL,CRSV,MONO,slnt,wght@0..1,0..1,0..1,-15..0,300..1000",
    },
    tags: {
      mood: ["expressive", "experimental", "flexible"],
      era: ["2020s"],
      use: ["display", "code", "ui", "body"],
      personality: ["playful", "modern", "versatile"],
    },
    sampleText: { latin: SAMPLE.latin },
    designer: "Stephen Nixon (Arrow Type)",
  },

  /* ─────────── Latin serif (3) ─────────── */
  {
    id: "playfair-display",
    name: "Playfair Display",
    family: "serif",
    scripts: ["latin"],
    cssFamily: `"Playfair Display", serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 400, max: 900, default: 500 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Playfair+Display",
    description:
      "High-contrast display serif with transitional-era DNA. Does elegant editorial / fashion headlines well; wrong for body.",
    loader: { kind: "google", family: "Playfair+Display:wght@400..900" },
    tags: {
      mood: ["elegant", "editorial", "contrast"],
      era: ["timeless", "transitional"],
      use: ["display", "heading", "logo"],
      personality: ["sophisticated", "luxurious", "dramatic"],
    },
    sampleText: { latin: "An Elegant Argument for Type" },
    designer: "Claus Eggers Sørensen",
  },
  {
    id: "fraunces",
    name: "Fraunces",
    family: "serif",
    scripts: ["latin"],
    cssFamily: `"Fraunces", serif`,
    variable: true,
    axes: [
      { tag: "opsz", name: "Optical size", min: 9, max: 144, default: 24 },
      { tag: "wght", name: "Weight", min: 100, max: 900, default: 500 },
      { tag: "SOFT", name: "Softness", min: 0, max: 100, default: 30 },
      { tag: "WONK", name: "Wonk", min: 0, max: 1, default: 0 },
    ],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Fraunces",
    description:
      "Characterful display serif with Softness + Wonk axes. Push WONK=1 for the quirky alternate glyphs. Warm, human, slightly off-center.",
    loader: {
      kind: "google",
      family: "Fraunces:opsz,wght,SOFT,WONK@9..144,100..900,0..100,0..1",
    },
    tags: {
      mood: ["expressive", "warm", "characterful"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["quirky", "warm", "memorable"],
    },
    sampleText: { latin: "Warmth, with a wink" },
    designer: "Undercase Type",
  },
  {
    id: "newsreader",
    name: "Newsreader",
    family: "serif",
    scripts: ["latin"],
    cssFamily: `"Newsreader", serif`,
    variable: true,
    axes: [
      { tag: "opsz", name: "Optical size", min: 6, max: 72, default: 16 },
      { tag: "wght", name: "Weight", min: 200, max: 800, default: 400 },
    ],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Newsreader",
    description:
      "Readable long-form serif with optical-size axis. Designed for news interfaces; scales gracefully from caption to headline.",
    loader: { kind: "google", family: "Newsreader:opsz,wght@6..72,200..800" },
    tags: {
      mood: ["readable", "editorial", "calm"],
      era: ["contemporary"],
      use: ["body", "heading"],
      personality: ["thoughtful", "serious", "trustworthy"],
    },
    sampleText: { latin: "A paragraph you'll actually read" },
    designer: "Production Type",
  },

  /* ─────────── Display / retro (1) ─────────── */
  {
    id: "righteous",
    name: "Righteous",
    family: "display",
    scripts: ["latin"],
    cssFamily: `"Righteous", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Righteous",
    description:
      "Geometric retro display — reads as 70s–80s confident signage. Pairs well with soft-serif body.",
    loader: { kind: "google", family: "Righteous" },
    tags: {
      mood: ["retro", "confident", "geometric"],
      era: ["1970s", "1980s", "vintage"],
      use: ["display", "logo", "heading"],
      personality: ["vintage", "bold", "nostalgic"],
    },
    sampleText: { latin: "Never Lose Your Cool" },
    designer: "Astigmatic",
  },

  /* ─────────── Mono (2) ─────────── */
  {
    id: "jetbrains-mono",
    name: "JetBrains Mono",
    family: "mono",
    scripts: ["latin"],
    cssFamily: `"JetBrains Mono", monospace`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 800, default: 400 }],
    license: "OFL-1.1",
    source: "https://www.jetbrains.com/lp/mono/",
    description:
      "Designed for developers — big clear counters, ligature support. Comfortable on long reading, sharp on small text.",
    loader: { kind: "google", family: "JetBrains+Mono:wght@100..800" },
    tags: {
      mood: ["technical", "clear", "precise"],
      era: ["2020s"],
      use: ["code", "mono", "ui"],
      personality: ["developer", "precise", "readable"],
    },
    sampleText: { latin: "const design = 'intelligence'" },
    designer: "JetBrains",
  },
  {
    id: "ibm-plex-mono",
    name: "IBM Plex Mono",
    family: "mono",
    scripts: ["latin"],
    cssFamily: `"IBM Plex Mono", monospace`,
    variable: false,
    axes: [],
    weights: [300, 400, 500, 600, 700],
    license: "OFL-1.1",
    source: "https://github.com/IBM/plex",
    description:
      "IBM's corporate mono. Less playful than JetBrains, more institutional — fits documentation and technical writing.",
    loader: { kind: "google", family: "IBM+Plex+Mono:wght@300;400;500;600;700" },
    tags: {
      mood: ["technical", "corporate", "institutional"],
      era: ["contemporary"],
      use: ["code", "mono", "body"],
      personality: ["professional", "precise", "legible"],
    },
    sampleText: { latin: "# technical writing looks better here" },
    designer: "Mike Abbink + Bold Monday",
  },

  /* ─────────── Korean expansion (5) ─────────── */
  {
    id: "do-hyeon",
    name: "Do Hyeon",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Do Hyeon", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Do+Hyeon",
    description:
      "Woowa Brothers' 도현체. Bold, squat, friendly — reads as Korean street signage + modern poster.",
    loader: { kind: "google", family: "Do+Hyeon" },
    tags: {
      mood: ["bold", "rounded", "playful"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["friendly", "confident", "approachable"],
    },
    sampleText: { latin: "Sell it bold", hangul: "굵게 한 번 살아보자" },
    designer: "Woowa Brothers (우아한형제들)",
  },
  {
    id: "gowun-batang",
    name: "Gowun Batang",
    family: "serif",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gowun Batang", serif`,
    variable: false,
    axes: [],
    weights: [400, 700],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Gowun+Batang",
    description:
      "Warm Korean serif. Softer than Nanum Myeongjo — reads literary without feeling institutional.",
    loader: { kind: "google", family: "Gowun+Batang:wght@400;700" },
    tags: {
      mood: ["warm", "elegant", "calm"],
      era: ["contemporary"],
      use: ["body", "heading"],
      personality: ["gentle", "thoughtful", "humanist"],
    },
    sampleText: {
      latin: "A softer serif for the reading mind",
      hangul: "천천히 읽히는 문장을 위하여",
    },
    designer: "Gowun Batang",
  },
  {
    id: "nanum-gothic",
    name: "Nanum Gothic",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Nanum Gothic", sans-serif`,
    variable: false,
    axes: [],
    weights: [400, 700, 800],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Nanum+Gothic",
    description:
      "Naver's foundational Korean sans — the 2010s workhorse. Safe everywhere, recognized by every Korean user.",
    loader: { kind: "google", family: "Nanum+Gothic:wght@400;700;800" },
    tags: {
      mood: ["neutral", "clean", "foundational"],
      era: ["2010s", "contemporary"],
      use: ["body", "ui", "heading"],
      personality: ["universal", "safe", "familiar"],
    },
    sampleText: { latin: "The default is a design choice", hangul: "익숙함도 디자인이다" },
    designer: "Naver",
  },
  {
    id: "gaegu",
    name: "Gaegu",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gaegu", cursive`,
    variable: false,
    axes: [],
    weights: [300, 400, 700],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Gaegu",
    description:
      "Kid-handwritten Korean script. Chunky, irregular strokes — reads playful and unpolished, like a school notebook.",
    loader: { kind: "google", family: "Gaegu:wght@300;400;700" },
    tags: {
      mood: ["handwritten", "playful", "casual"],
      era: ["timeless"],
      use: ["display", "accent"],
      personality: ["personal", "cute", "authentic"],
    },
    sampleText: { latin: "Schoolyard notes", hangul: "엉성한 손글씨의 매력" },
  },
  {
    id: "hahmlet",
    name: "Hahmlet",
    family: "serif",
    scripts: ["latin", "hangul"],
    cssFamily: `"Hahmlet", serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 500 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Hahmlet",
    description:
      "Contemporary Korean serif with variable weight. More contrast than Gowun Batang — reads editorial and modern.",
    loader: { kind: "google", family: "Hahmlet:wght@100..900" },
    tags: {
      mood: ["elegant", "editorial", "modern"],
      era: ["2020s"],
      use: ["display", "heading", "body"],
      personality: ["sophisticated", "contemporary", "deliberate"],
    },
    sampleText: {
      latin: "Editorial serif, Korean variable",
      hangul: "현대적 한글 가변 세리프",
    },
    designer: "Ethan Nakache",
  },

  /* ─────────── Latin expansion (10) ─────────── */
  {
    id: "dm-sans",
    name: "DM Sans",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"DM Sans", sans-serif`,
    variable: true,
    axes: [
      { tag: "opsz", name: "Optical size", min: 9, max: 40, default: 14 },
      { tag: "wght", name: "Weight", min: 100, max: 1000, default: 400 },
    ],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/DM+Sans",
    description:
      "Google's in-house low-contrast sans. Optical-size axis makes it work at 10px captions and 96px display without swapping families.",
    loader: { kind: "google", family: "DM+Sans:opsz,wght@9..40,100..1000" },
    tags: {
      mood: ["clean", "geometric", "friendly"],
      era: ["2020s"],
      use: ["ui", "body", "display"],
      personality: ["modern", "approachable", "balanced"],
    },
    sampleText: { latin: "Scale gracefully from caption to headline" },
    designer: "Colophon Foundry",
  },
  {
    id: "space-grotesk",
    name: "Space Grotesk",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Space Grotesk", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 300, max: 700, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Space+Grotesk",
    description:
      "Proportional evolution of Space Mono. Technical-but-humane — reads like something a well-rested engineer designed.",
    loader: { kind: "google", family: "Space+Grotesk:wght@300..700" },
    tags: {
      mood: ["geometric", "modern", "technical"],
      era: ["2020s"],
      use: ["display", "ui", "heading"],
      personality: ["futuristic", "precise", "quirky"],
    },
    sampleText: { latin: "Designed from a monospace" },
    designer: "Florian Karsten",
  },
  {
    id: "outfit",
    name: "Outfit",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Outfit", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Outfit",
    description:
      "Geometric sans with a warm twist — slightly softer than Montserrat, more rhythmic than Poppins. Reads modern without shouting it.",
    loader: { kind: "google", family: "Outfit:wght@100..900" },
    tags: {
      mood: ["geometric", "clean", "modern"],
      era: ["2020s"],
      use: ["ui", "display", "heading"],
      personality: ["modern", "balanced", "confident"],
    },
    sampleText: { latin: "A new geometric, gently" },
    designer: "Rodrigo Fuenzalida",
  },
  {
    id: "poppins",
    name: "Poppins",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Poppins", sans-serif`,
    variable: false,
    axes: [],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Poppins",
    description:
      "The most-downloaded Google Font globally. Pure geometric sans, rounded terminals. Safe everywhere, maybe too safe.",
    loader: { kind: "google", family: "Poppins:wght@100;200;300;400;500;600;700;800;900" },
    tags: {
      mood: ["geometric", "friendly", "universal"],
      era: ["2010s", "2020s"],
      use: ["ui", "body", "display"],
      personality: ["approachable", "rounded", "popular"],
    },
    sampleText: { latin: "Rounded geometric, everywhere" },
    designer: "Indian Type Foundry",
  },
  {
    id: "lora",
    name: "Lora",
    family: "serif",
    scripts: ["latin"],
    cssFamily: `"Lora", serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 400, max: 700, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Lora",
    description:
      "Calligraphic serif made for long reading. Warmer than Crimson, more literary than Newsreader. The blog-post default.",
    loader: { kind: "google", family: "Lora:wght@400..700" },
    tags: {
      mood: ["readable", "elegant", "warm"],
      era: ["contemporary", "timeless"],
      use: ["body", "heading"],
      personality: ["thoughtful", "literary", "gentle"],
    },
    sampleText: { latin: "Sentences want to be read slowly" },
    designer: "Cyreal",
  },
  {
    id: "work-sans",
    name: "Work Sans",
    family: "sans",
    scripts: ["latin"],
    cssFamily: `"Work Sans", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Work+Sans",
    description:
      "Transitional workhorse — optimised for on-screen text between 14-48px. Middle ground between Inter's cold and Manrope's warm.",
    loader: { kind: "google", family: "Work+Sans:wght@100..900" },
    tags: {
      mood: ["clean", "workhorse", "transitional"],
      era: ["2010s", "2020s"],
      use: ["ui", "body", "display"],
      personality: ["versatile", "pragmatic", "balanced"],
    },
    sampleText: { latin: "The sans that just works" },
    designer: "Wei Huang",
  },
  {
    id: "crimson-pro",
    name: "Crimson Pro",
    family: "serif",
    scripts: ["latin"],
    cssFamily: `"Crimson Pro", serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 200, max: 900, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Crimson+Pro",
    description:
      "Old-style book serif, refined. Reads print-quality long-form — pairs well with serious body copy.",
    loader: { kind: "google", family: "Crimson+Pro:wght@200..900" },
    tags: {
      mood: ["classical", "readable", "elegant"],
      era: ["timeless"],
      use: ["body", "heading"],
      personality: ["literary", "traditional", "serious"],
    },
    sampleText: { latin: "On the quality of long reading" },
    designer: "Jacques Le Bailly",
  },
  {
    id: "caveat",
    name: "Caveat",
    family: "handwritten",
    scripts: ["latin"],
    cssFamily: `"Caveat", cursive`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 400, max: 700, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Caveat",
    description:
      "Casual brush-ink script. Reads like marker on whiteboard — use for annotation layer over clean body, not as body itself.",
    loader: { kind: "google", family: "Caveat:wght@400..700" },
    tags: {
      mood: ["handwritten", "casual", "personal"],
      era: ["timeless"],
      use: ["accent", "display", "annotation"],
      personality: ["warm", "authentic", "quick"],
    },
    sampleText: { latin: "annotation beats illustration" },
    designer: "Pablo Impallari",
  },
  {
    id: "space-mono",
    name: "Space Mono",
    family: "mono",
    scripts: ["latin"],
    cssFamily: `"Space Mono", monospace`,
    variable: false,
    axes: [],
    weights: [400, 700],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Space+Mono",
    description:
      "Retro-futurist mono. More character than JetBrains, less corporate than IBM Plex — good for hero code blocks and display.",
    loader: { kind: "google", family: "Space+Mono:wght@400;700" },
    tags: {
      mood: ["retro", "technical", "distinctive"],
      era: ["retro", "2010s"],
      use: ["code", "display"],
      personality: ["quirky", "futuristic", "characterful"],
    },
    sampleText: { latin: "echo 'hello, retro-future'" },
    designer: "Colophon Foundry",
  },
  {
    id: "bebas-neue",
    name: "Bebas Neue",
    family: "display",
    scripts: ["latin"],
    cssFamily: `"Bebas Neue", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Bebas+Neue",
    description:
      "Tall-and-narrow condensed display sans. One of the most-used display fonts on the web. Poster energy by default.",
    loader: { kind: "google", family: "Bebas+Neue" },
    tags: {
      mood: ["bold", "condensed", "impactful"],
      era: ["timeless"],
      use: ["display", "logo", "heading"],
      personality: ["confident", "editorial", "poster"],
    },
    sampleText: { latin: "POSTER ENERGY" },
    designer: "Ryoichi Tsunekawa",
  },

  /* ─────────── Korean handwritten / calligraphy (5) ─────────── */
  {
    id: "cute-font",
    name: "Cute Font",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Cute Font", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Cute+Font",
    description:
      "Chunky Korean handwritten script, wide round strokes. Reads as kid-diary or YouTube title — unpolished charm.",
    loader: { kind: "google", family: "Cute+Font" },
    tags: {
      mood: ["handwritten", "playful", "casual", "warm"],
      era: ["contemporary"],
      use: ["display", "accent"],
      personality: ["personal", "cute", "authentic"],
    },
    sampleText: { latin: "Cute and chunky", hangul: "귀엽고 둔탁한 손글씨" },
  },
  {
    id: "east-sea-dokdo",
    name: "East Sea Dokdo",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"East Sea Dokdo", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/East+Sea+Dokdo",
    description:
      "Korean brush-pen calligraphy. Irregular strokes with pressure variation — reads as 붓글씨 energy, not ballpoint.",
    loader: { kind: "google", family: "East+Sea+Dokdo" },
    tags: {
      mood: ["handwritten", "expressive", "calligraphy"],
      era: ["timeless"],
      use: ["display", "accent", "logo"],
      personality: ["personal", "authentic", "artistic"],
    },
    sampleText: { latin: "Brush strokes speak", hangul: "붓놀림에 기운이 담긴다" },
  },
  {
    id: "kirang-haerang",
    name: "Kirang Haerang",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Kirang Haerang", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Kirang+Haerang",
    description:
      "Warm Korean handwritten with subtle Japanese katakana influence. Friendly, rhythmic — good for zine-style display.",
    loader: { kind: "google", family: "Kirang+Haerang" },
    tags: {
      mood: ["handwritten", "playful", "warm"],
      era: ["contemporary"],
      use: ["display", "accent"],
      personality: ["personal", "characterful", "quirky"],
    },
    sampleText: { latin: "Zine-ready handwritten", hangul: "손으로 쓴 잡지 느낌" },
  },
  {
    id: "dokdo",
    name: "Dokdo",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Dokdo", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Dokdo",
    description:
      "Bold marker-pen Korean script. Thicker and more assertive than Nanum Pen — poster-friendly at large sizes.",
    loader: { kind: "google", family: "Dokdo" },
    tags: {
      mood: ["handwritten", "bold", "impactful"],
      era: ["contemporary"],
      use: ["display", "logo", "heading"],
      personality: ["confident", "authentic", "characterful"],
    },
    sampleText: { latin: "Marker-pen presence", hangul: "매직으로 힘껏 써내린" },
  },
  {
    id: "song-myung",
    name: "Song Myung",
    family: "serif",
    scripts: ["latin", "hangul"],
    cssFamily: `"Song Myung", serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Song+Myung",
    description:
      "Classical Korean 명조체 serif. Traditional, stately — reads as textbook or official document.",
    loader: { kind: "google", family: "Song+Myung" },
    tags: {
      mood: ["classical", "readable", "calm"],
      era: ["timeless"],
      use: ["body", "heading"],
      personality: ["traditional", "thoughtful", "serious"],
    },
    sampleText: { latin: "A classical Korean serif", hangul: "정갈한 명조체의 맛" },
  },

  /* ─────────── Korean — expanded (Google Fonts, 18) ─────────── */
  {
    id: "noto-serif-kr",
    name: "Noto Serif KR",
    family: "serif",
    scripts: ["latin", "hangul"],
    cssFamily: `"Noto Serif KR", serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 200, max: 900, default: 400 }],
    license: "OFL-1.1",
    source: "https://fonts.google.com/noto/specimen/Noto+Serif+KR",
    description:
      "Universal Korean 명조체. Serif counterpart to Noto Sans KR — stately, readable, reliable for editorial long-form.",
    loader: { kind: "google", family: "Noto+Serif+KR:wght@200..900" },
    tags: {
      mood: ["editorial", "readable", "classical"],
      era: ["timeless"],
      use: ["body", "heading"],
      personality: ["traditional", "serious", "universal"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "Adobe + Google",
  },
  {
    id: "nanum-myeongjo",
    name: "Nanum Myeongjo",
    family: "serif",
    scripts: ["latin", "hangul"],
    cssFamily: `"Nanum Myeongjo", serif`,
    variable: false,
    axes: [],
    weights: [400, 700, 800],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Nanum+Myeongjo",
    description:
      "Naver's 나눔명조. The default Korean editorial serif — quiet, literary, reads like a book.",
    loader: { kind: "google", family: "Nanum+Myeongjo:wght@400;700;800" },
    tags: {
      mood: ["editorial", "calm", "readable"],
      era: ["timeless"],
      use: ["body", "heading"],
      personality: ["literary", "thoughtful", "traditional"],
    },
    sampleText: { latin: "Books feel like books", hangul: "책이 책처럼 느껴지는 글꼴" },
    designer: "Naver",
  },
  {
    id: "nanum-brush-script",
    name: "Nanum Brush Script",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Nanum Brush Script", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Nanum+Brush+Script",
    description:
      "Naver's 나눔손글씨 붓. Broad wet brush — looks painted rather than written. Good for warm celebratory copy.",
    loader: { kind: "google", family: "Nanum+Brush+Script" },
    tags: {
      mood: ["handwritten", "warm", "expressive"],
      era: ["timeless"],
      use: ["display", "accent"],
      personality: ["personal", "celebratory", "characterful"],
    },
    sampleText: { latin: "Painted, not written", hangul: "쓴 게 아니라 그린 느낌" },
    designer: "Naver",
  },
  {
    id: "nanum-gothic-coding",
    name: "Nanum Gothic Coding",
    family: "mono",
    scripts: ["latin", "hangul"],
    cssFamily: `"Nanum Gothic Coding", monospace`,
    variable: false,
    axes: [],
    weights: [400, 700],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Nanum+Gothic+Coding",
    description:
      "Monospaced Korean sans for code + tabular data. One of the few free monos that handles Hangul glyph widths cleanly.",
    loader: { kind: "google", family: "Nanum+Gothic+Coding:wght@400;700" },
    tags: {
      mood: ["technical", "neutral", "readable"],
      era: ["timeless"],
      use: ["code", "body"],
      personality: ["professional", "pragmatic", "universal"],
    },
    sampleText: { latin: "const font = 'code';", hangul: "콘솔·로그·표에 제격" },
    designer: "Naver",
  },
  {
    id: "gothic-a1",
    name: "Gothic A1",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gothic A1", sans-serif`,
    variable: false,
    axes: [],
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Gothic+A1",
    description:
      "Nine-weight geometric Korean sans. Cleaner than Noto Sans KR, a sharper default for modern product UI.",
    loader: { kind: "google", family: "Gothic+A1:wght@100;200;300;400;500;600;700;800;900" },
    tags: {
      mood: ["clean", "geometric", "modern"],
      era: ["2020s"],
      use: ["ui", "body", "display"],
      personality: ["professional", "precise", "modern"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "HanType",
  },
  {
    id: "gugi",
    name: "Gugi",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gugi", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Gugi",
    description:
      "Wobbly, hand-drawn-feel Korean display. Irregular edges read as playful — wrong for serious chrome, right for kid-brand energy.",
    loader: { kind: "google", family: "Gugi" },
    tags: {
      mood: ["playful", "quirky", "warm"],
      era: ["contemporary"],
      use: ["display", "logo"],
      personality: ["friendly", "characterful", "casual"],
    },
    sampleText: { latin: "Feels hand-drawn", hangul: "손으로 쓱쓱 그린 듯한" },
  },
  {
    id: "hi-melody",
    name: "Hi Melody",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Hi Melody", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Hi+Melody",
    description:
      "Teen-diary handwritten KR. Round, cheerful, slightly juvenile — nostalgic in the right context.",
    loader: { kind: "google", family: "Hi+Melody" },
    tags: {
      mood: ["handwritten", "playful", "warm"],
      era: ["contemporary"],
      use: ["display", "accent"],
      personality: ["personal", "cute", "youthful"],
    },
    sampleText: { latin: "Happy little notes", hangul: "오늘도 고마워요" },
  },
  {
    id: "dongle",
    name: "Dongle",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Dongle", sans-serif`,
    variable: false,
    axes: [],
    weights: [300, 400, 700],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Dongle",
    description:
      "Wide, slightly stretched Korean display. Retro 90s signage energy — feels like a Seoul back-alley shop sign.",
    loader: { kind: "google", family: "Dongle:wght@300;400;700" },
    tags: {
      mood: ["retro", "warm", "nostalgic"],
      era: ["1990s", "retro"],
      use: ["display", "logo"],
      personality: ["friendly", "local", "characterful"],
    },
    sampleText: { latin: "Back-alley signage", hangul: "골목 간판처럼" },
  },
  {
    id: "poor-story",
    name: "Poor Story",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Poor Story", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Poor+Story",
    description:
      "Scratchy, uneven Korean handwriting. Comic-strip captions, zine annotation — feels improvised on purpose.",
    loader: { kind: "google", family: "Poor+Story" },
    tags: {
      mood: ["handwritten", "casual", "imperfect"],
      era: ["contemporary"],
      use: ["display", "accent"],
      personality: ["personal", "authentic", "quirky"],
    },
    sampleText: { latin: "Scribbled margins", hangul: "끄적인 메모 같은" },
  },
  {
    id: "single-day",
    name: "Single Day",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Single Day", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Single+Day",
    description:
      "Tall, narrow Korean display with a poster-like cadence. Works as an accent — not for running text.",
    loader: { kind: "google", family: "Single+Day" },
    tags: {
      mood: ["editorial", "expressive", "narrow"],
      era: ["contemporary"],
      use: ["display", "heading"],
      personality: ["confident", "poetic", "distinct"],
    },
    sampleText: { latin: "Poster day", hangul: "한 장의 포스터처럼" },
  },
  {
    id: "stylish",
    name: "Stylish",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Stylish", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Stylish",
    description:
      "Elegant, narrow Korean sans with high contrast. Fashion/boutique feel — editorial but not serif.",
    loader: { kind: "google", family: "Stylish" },
    tags: {
      mood: ["elegant", "editorial", "luxurious"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["sophisticated", "refined", "modern"],
    },
    sampleText: { latin: "Boutique poise", hangul: "편집샵의 우아함" },
  },
  {
    id: "sunflower",
    name: "Sunflower",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Sunflower", sans-serif`,
    variable: false,
    axes: [],
    weights: [300, 500, 700],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Sunflower",
    description:
      "Geometric KR sans with open counters. Breathable at small sizes — a gentle alternative to Noto Sans KR for body.",
    loader: { kind: "google", family: "Sunflower:wght@300;500;700" },
    tags: {
      mood: ["clean", "soft", "friendly"],
      era: ["2010s", "2020s"],
      use: ["ui", "body"],
      personality: ["approachable", "balanced", "gentle"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
  },
  {
    id: "yeon-sung",
    name: "Yeon Sung",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Yeon Sung", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Yeon+Sung",
    description:
      "Brushy, rounded KR display. Feels like calligraphy with an attitude — good for food, drink, street-culture brands.",
    loader: { kind: "google", family: "Yeon+Sung" },
    tags: {
      mood: ["playful", "bold", "warm"],
      era: ["contemporary"],
      use: ["display", "logo"],
      personality: ["characterful", "bold", "friendly"],
    },
    sampleText: { latin: "Street kitchen vibe", hangul: "분식집 간판 느낌" },
  },
  {
    id: "gamja-flower",
    name: "Gamja Flower",
    family: "handwritten",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gamja Flower", cursive`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Gamja+Flower",
    description:
      "Loose, marker-tip KR handwriting. Childlike without being twee — friendly captions, sticker text, DIY zines.",
    loader: { kind: "google", family: "Gamja+Flower" },
    tags: {
      mood: ["handwritten", "casual", "warm"],
      era: ["contemporary"],
      use: ["display", "accent"],
      personality: ["personal", "approachable", "playful"],
    },
    sampleText: { latin: "Sticker style", hangul: "스티커 손글씨처럼" },
  },
  {
    id: "ibm-plex-sans-kr",
    name: "IBM Plex Sans KR",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"IBM Plex Sans KR", sans-serif`,
    variable: false,
    axes: [],
    weights: [100, 200, 300, 400, 500, 600, 700],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/IBM+Plex+Sans+KR",
    description:
      "IBM Plex extended to Korean. Crisp, slightly technical — reads as considered product chrome. Pairs with Plex Mono/Serif cleanly.",
    loader: { kind: "google", family: "IBM+Plex+Sans+KR:wght@100;200;300;400;500;600;700" },
    tags: {
      mood: ["clean", "technical", "modern"],
      era: ["2020s"],
      use: ["ui", "body", "display"],
      personality: ["professional", "precise", "considered"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "Bold Monday + IBM",
  },
  {
    id: "diphylleia",
    name: "Diphylleia",
    family: "serif",
    scripts: ["latin", "hangul"],
    cssFamily: `"Diphylleia", serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Diphylleia",
    description:
      "Delicate high-contrast KR serif. Editorial display with a translucent feel — named for the Korean 'skeleton flower'.",
    loader: { kind: "google", family: "Diphylleia" },
    tags: {
      mood: ["elegant", "editorial", "luxurious"],
      era: ["contemporary"],
      use: ["display", "heading"],
      personality: ["refined", "poetic", "sophisticated"],
    },
    sampleText: { latin: "Translucent serif", hangul: "투명한 명조의 기품" },
  },
  {
    id: "gasoek-one",
    name: "Gasoek One",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gasoek One", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Gasoek+One",
    description:
      "Super-heavy KR display. Filled-in counters, shout-poster presence — pairs with thin sans for maximum contrast.",
    loader: { kind: "google", family: "Gasoek+One" },
    tags: {
      mood: ["bold", "impactful", "loud"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["assertive", "confident", "strong"],
    },
    sampleText: { latin: "HEADLINE FUEL", hangul: "확성기처럼 외치기" },
  },
  {
    id: "black-and-white-picture",
    name: "Black And White Picture",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Black And White Picture", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "OFL-1.1",
    source: "https://fonts.google.com/specimen/Black+And+White+Picture",
    description:
      "Chunky, stamp-like KR display. Reads as pop-art poster — 60s advertising energy.",
    loader: { kind: "google", family: "Black+And+White+Picture" },
    tags: {
      mood: ["retro", "bold", "expressive"],
      era: ["1960s", "retro"],
      use: ["display", "logo"],
      personality: ["vintage", "confident", "characterful"],
    },
    sampleText: { latin: "POP POSTER", hangul: "광고포스터 감성" },
  },

  /* ─────────── Korean — noonnu / jsdelivr (6) ─────────── */
  {
    id: "gmarket-sans",
    name: "Gmarket Sans",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Gmarket Sans", sans-serif`,
    variable: false,
    axes: [],
    weights: [300, 500, 700],
    license: "Gmarket — free commercial use",
    source: "https://company.gmarket.co.kr/company/about/company/company--font.asp",
    description:
      "G마켓 브랜드 산세리프. 가벼우면서도 또렷한 카운터 — 이커머스·이벤트 배너에 자주 보이는 얼굴.",
    loader: {
      kind: "jsdelivr",
      fontFaceCss:
        "@import url('https://cdn.jsdelivr.net/gh/fonts-archive/GmarketSans/GmarketSans.css');",
    },
    tags: {
      mood: ["clean", "modern", "friendly"],
      era: ["2010s", "2020s"],
      use: ["display", "heading", "ui"],
      personality: ["professional", "approachable", "commercial"],
    },
    sampleText: { latin: "Commerce-ready sans", hangul: "커머스에 어울리는 얼굴" },
    designer: "G마켓",
  },
  {
    id: "spoqa-han-sans-neo",
    name: "Spoqa Han Sans Neo",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"Spoqa Han Sans Neo", sans-serif`,
    variable: false,
    axes: [],
    weights: [100, 300, 400, 500, 700],
    license: "OFL-1.1",
    source: "https://spoqa.github.io/spoqa-han-sans/",
    description:
      "Spoqa가 깎은 한영 산세리프. Noto Sans KR보다 살짝 미니멀하고 현대적 — 국내 스타트업 UI의 오랜 기본값.",
    loader: {
      kind: "jsdelivr",
      fontFaceCss:
        "@import url('https://spoqa.github.io/spoqa-han-sans/css/SpoqaHanSansNeo.css');",
    },
    tags: {
      mood: ["clean", "modern", "neutral"],
      era: ["2010s", "2020s"],
      use: ["ui", "body", "heading"],
      personality: ["professional", "minimal", "balanced"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "Spoqa",
  },
  {
    id: "bm-hanna-pro",
    name: "BM Hanna Pro",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"BM HANNA Pro", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "Woowa — free commercial use",
    source: "https://www.woowahan.com/fonts",
    description:
      "우아한형제들 한나체 Pro. 둥글한 획과 삐뚤빼뚤한 중심선 — 배달 브랜드의 친근한 손글씨 느낌.",
    loader: {
      kind: "jsdelivr",
      fontFaceCss:
        "@import url('https://cdn.jsdelivr.net/gh/fonts-archive/BMHANNAPro/BMHANNAPro.css');",
    },
    tags: {
      mood: ["playful", "warm", "handwritten"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["friendly", "quirky", "authentic"],
    },
    sampleText: { latin: "Delivery brand feel", hangul: "배달 브랜드의 손글씨" },
    designer: "Woowa Brothers (우아한형제들)",
  },
  {
    id: "yg-jalnan",
    name: "YG 여기어때 잘난체",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Jalnan", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "YG — free commercial use",
    source: "https://noonnu.cc/font_page/162",
    description:
      "여기어때 '잘난체'. 과장된 세리프 장식 + 두꺼운 획 — 관종 에너지. 한 줄짜리 포스터 헤드라인용.",
    loader: {
      kind: "jsdelivr",
      fontFaceCss:
        "@import url('https://cdn.jsdelivr.net/gh/fonts-archive/Jalnan/Jalnan.css');",
    },
    tags: {
      mood: ["bold", "expressive", "playful"],
      era: ["contemporary"],
      use: ["display", "heading"],
      personality: ["confident", "loud", "characterful"],
    },
    sampleText: { latin: "LOOK-AT-ME HEADER", hangul: "잘난 헤드라인" },
    designer: "여기어때",
  },
  {
    id: "cafe24-ssurround",
    name: "Cafe24 Ssurround",
    family: "display",
    scripts: ["latin", "hangul"],
    cssFamily: `"Cafe24 Ssurround", sans-serif`,
    variable: false,
    axes: [],
    weights: [400],
    license: "Cafe24 — free commercial use",
    source: "https://fonts.cafe24.com/",
    description:
      "Cafe24 쓰라운드체. 둥글한 모서리 + 두꺼운 획 — 여름·펑키 감성. 이벤트/프로모션 히어로에 자주 쓰임.",
    loader: {
      kind: "jsdelivr",
      fontFaceCss:
        "@import url('https://cdn.jsdelivr.net/gh/fonts-archive/Cafe24Ssurround/Cafe24Ssurround.css');",
    },
    tags: {
      mood: ["playful", "bold", "retro"],
      era: ["contemporary"],
      use: ["display", "heading", "logo"],
      personality: ["friendly", "energetic", "characterful"],
    },
    sampleText: { latin: "SUMMER VIBE", hangul: "여름 이벤트 포스터" },
    designer: "Cafe24",
  },
  {
    id: "suit-variable",
    name: "SUIT Variable",
    family: "sans",
    scripts: ["latin", "hangul"],
    cssFamily: `"SUIT Variable", "SUIT", sans-serif`,
    variable: true,
    axes: [{ tag: "wght", name: "Weight", min: 100, max: 900, default: 500 }],
    license: "OFL-1.1",
    source: "https://github.com/sun-typeface/SUIT",
    description:
      "선언(Sunn.us) SUIT. Pretendard의 대안으로 요즘 스타트업들이 자주 고르는 모던 한영 sans. 조금 더 단단한 무게감.",
    loader: {
      kind: "jsdelivr",
      fontFaceCss:
        "@import url('https://cdn.jsdelivr.net/gh/sunn-us/SUIT/fonts/variable/woff2/SUIT-Variable.css');",
    },
    tags: {
      mood: ["clean", "modern", "neutral"],
      era: ["2020s"],
      use: ["ui", "body", "display"],
      personality: ["professional", "modern", "precise"],
    },
    sampleText: { latin: SAMPLE.latin, hangul: SAMPLE.hangul },
    designer: "선언 (Sunn.us)",
  },
];

/** Quick index by id. */
export const FONT_BY_ID: Record<string, FontEntry> = Object.fromEntries(
  FONT_CATALOG.map((f) => [f.id, f]),
);

/** All unique mood tags across the catalog — used to populate filter chips. */
export function allMoods(): string[] {
  const set = new Set<string>();
  for (const f of FONT_CATALOG) for (const m of f.tags.mood) set.add(m);
  return [...set].sort();
}

/** Mood tag → how many catalog entries carry it. Used to surface the
 *  most-representative moods up-front so the filter isn't a wall of 40+
 *  equally-weighted chips. */
export function moodFrequency(): Map<string, number> {
  const freq = new Map<string, number>();
  for (const f of FONT_CATALOG)
    for (const m of f.tags.mood) freq.set(m, (freq.get(m) ?? 0) + 1);
  return freq;
}

/** Semantic buckets over the full mood taxonomy. Anything not listed here
 *  falls into "other" and surfaces in the extended panel — no tag is ever
 *  silently dropped. */
export const MOOD_BUCKETS: { id: string; label: string; moods: string[] }[] = [
  {
    id: "feel",
    label: "Feel",
    moods: [
      "warm", "soft", "friendly", "playful", "bold", "elegant", "luxurious",
      "quirky", "confident", "calm", "nostalgic", "casual", "personal",
      "loud", "imperfect", "assertive",
    ],
  },
  {
    id: "form",
    label: "Form",
    moods: [
      "clean", "modern", "sharp", "rounded", "condensed", "narrow",
      "geometric", "calligraphy", "handwritten", "classical", "transitional",
      "experimental", "neutral", "foundational", "contrast", "characterful",
      "distinctive", "expressive",
    ],
  },
  {
    id: "use",
    label: "Purpose",
    moods: [
      "editorial", "readable", "workhorse", "universal", "corporate",
      "institutional", "technical", "precise", "clear", "impactful",
      "flexible", "retro",
    ],
  },
];

/** All unique use tags — filter chips. */
export function allUses(): string[] {
  const set = new Set<string>();
  for (const f of FONT_CATALOG) for (const u of f.tags.use) set.add(u);
  return [...set].sort();
}
