import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/research-data-deletion'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-deletion-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','research-data-deletion','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-deletion-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield deletion approval oracle and mutant calibration',()=>{
  it('accepts progressive-panel and review-step implementations',()=>{for(const source of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
  it('kills confirmation bypass',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`bypass-${source}`,(html,key)=>key==='oracle-a'?html.replace("const ok=ack.checked&&phrase.value.trim()==='DELETE SAMPLE COASTAL SURVEY'","const ok=phrase.value.trim().length>0"):html.replace("const valid=ack.checked&&phrase.value.trim()==='REMOVE SAMPLE ARCTIC NOTES'","const valid=phrase.value.trim().length>0")),`bypass-${source}`);expect(result.assertions.approve_requires_both_gates).toBe(false)}},60_000);
  it('kills flattened scope hierarchy',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`flat-${source}`,(html,key)=>key==='oracle-a'?html.replace(/<div class="scope-root">[\s\S]*?<\/div><\/section>/,'<p>Dataset Sample coastal survey includes 42 records, 6 attachments, and 3 views.</p></section>'):html.replace(/<div class="dataset">[\s\S]*?<\/div><p><button/,'<p>Parent dataset Sample Arctic Notes includes 18 entries, 4 media files, and 2 annotations.</p><p><button')),`flat-${source}`);expect(result.assertions.scope_parent_child_hierarchy).toBe(false)}},60_000);
  it('kills a hidden cancel path',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`cancel-${source}`,html=>html.replace('</style>','.cancel,#cancel-action{display:none!important}</style>')),`cancel-${source}`);expect(result.assertions.cancel_keyboard_reachable).toBe(false)}},60_000);
});
