import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/public-record-search'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-search-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','public-record-search','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-search-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield public record search oracle and mutant calibration',()=>{
  it('accepts sidebar-route and toolbar-dialog implementations',()=>{for(const source of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
  it('kills invisible active filter state',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`invisible-${source}`,html=>html.replace('</style>','[aria-label="Active filters"]{display:none!important}</style>')),`invisible-${source}`);expect(result.assertions.active_filter_values_visible).toBe(false)}},60_000);
  it('kills broken clear-filters behavior',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`clear-${source}`,html=>html.replace(/clear\.onclick=\(\)=>\{[^}]+\}/,'clear.onclick=()=>{}')),`clear-${source}`);expect(result.assertions.clear_contract_honored).toBe(false)}},60_000);
  it('kills missing no-results state',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`empty-${source}`,html=>html.replace('</style>','#empty{display:none!important}</style>')),`empty-${source}`);expect(result.assertions.no_results_distinct).toBe(false)}},60_000);
});
