import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/community-class-checkout'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-checkout-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','community-class-checkout','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-checkout-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield checkout oracle and mutant calibration',()=>{
it('accepts inline and stepped implementations',()=>{for(const s of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,s),`valid-${s}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
it('kills an obscured pre-confirm total',()=>{for(const s of['oracle-a','oracle-b']){const r=evaluate(mutant(s,`total-${s}`,h=>h.replace('</style>','.total{display:none!important}</style>')),`total-${s}`);expect(r.assertions.total_visible_before_confirm).toBe(false)}},60_000);
it('kills malformed-email acceptance',()=>{for(const s of['oracle-a','oracle-b']){const r=evaluate(mutant(s,`email-${s}`,(h,k)=>k==='oracle-a'?h.replace("emailOK=/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email.value)","emailOK=email.value.length>0"):h.replace("okMail=/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(mail.value)","okMail=mail.value.length>0")),`email-${s}`);expect(r.assertions.invalid_email_blocked).toBe(false)}},60_000);
it('kills premature success copy',()=>{for(const s of['oracle-a','oracle-b']){const r=evaluate(mutant(s,`success-${s}`,h=>h.replace('<h1>','<p>Payment successful.</p><h1>')),`success-${s}`);expect(r.assertions.no_premature_success).toBe(false)}},60_000);
});
