import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/mobile-transit-report'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-transit-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','mobile-transit-report','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-transit-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield transit oracle and mutant calibration',()=>{
  it('accepts stepper and single-page review implementations',()=>{for(const source of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
  it('kills a mobile touch target below 44px',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`touch-${source}`,(html,key)=>key==='oracle-a'?html.replace('.issue-option{min-height:48px','.issue-option{min-height:32px').replace('button{min-height:48px','button{min-height:32px'):html.replace('select,textarea,button{width:100%;min-height:48px','select,textarea,button{width:100%;min-height:32px')),`touch-${source}`);expect(result.assertions.responsive).toBe(false)}},60_000);
  it('kills a skipped review step',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`review-${source}`,(html,key)=>key==='oracle-a'?html.replace('draft.hidden=true;review.hidden=false','draft.hidden=true;review.hidden=true;submitted.hidden=false'):html.replace('empty.hidden=true;data.hidden=false;submit.hidden=false','empty.hidden=true;data.hidden=true;submit.hidden=true;done.hidden=false')),`review-${source}`);expect(result.assertions.review_required_before_submit).toBe(false)}},60_000);
  it('kills an assumed precise location',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`location-${source}`,html=>html.replace('</header>','<p>Precise location: Central Station platform 2.</p></header>').replace('</h1>','</h1><p>Precise location: Central Station platform 2.</p>')),`location-${source}`);expect(result.assertions.no_preconsent_geolocation).toBe(false)}},60_000);
});
