import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/volunteer-import-recovery'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-recovery-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','volunteer-import-recovery','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-recovery-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield recovery oracle and mutant calibration',()=>{
  it('accepts file-table and local-sample-card implementations',()=>{for(const source of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
  it('kills an unrecoverable row error',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`row-${source}`,html=>html.replace(/<button (?:class="row-action" )?id="exclude"[^>]*>[^<]+<\/button>/,'<span>Contact an administrator</span>')),`row-${source}`);expect(result.assertions.row_error_associated_and_recoverable).toBe(false)}},60_000);
  it('kills retry that loses preserved valid rows',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`preserve-${source}`,html=>html.replace(/Imported 2 fictional sample rows: Alex Sample and Mina Sample\. 0 invalid rows remain\./,'Imported 0 sample rows. 0 invalid rows remain.').replace(/2 of 2 fictional sample rows imported: Alex Example and Mina Example\. 0 errors remain\./,'0 of 2 sample rows imported. 0 errors remain.')),`preserve-${source}`);expect(result.assertions.valid_row_identities_preserved).toBe(false)}},60_000);
  it('kills ambiguous completion counts',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`count-${source}`,html=>html.replace(/Imported 2 fictional sample rows: Alex Sample and Mina Sample\. 0 invalid rows remain\./,'Sample import complete.').replace(/2 of 2 fictional sample rows imported: Alex Example and Mina Example\. 0 errors remain\./,'Sample import complete.')),`count-${source}`);expect(result.assertions.completion_counts_unambiguous).toBe(false)}},60_000);
});
