import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/clinic-visit-prep-locales'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-locale-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','clinic-visit-prep-locales','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-locale-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield five-locale oracle and mutant calibration',()=>{
  it('accepts native-select and language-button implementations',()=>{for(const source of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},90_000);
  it('kills locale label and html-lang mismatch',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`lang-${source}`,html=>html.replace('document.documentElement.lang=code','document.documentElement.lang=code===\'zh-TW\'?\'zh-CN\':code')),`lang-${source}`);expect(result.assertions.selected_label_lang_script_agree).toBe(false)}},90_000);
  it('kills CJK horizontal overflow',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`overflow-${source}`,(html,key)=>key==='oracle-a'?html.replace('.checklist{background:', '.checklist{min-width:700px;background:'):html.replace('.checklist,.progress-card{background:', '.checklist{min-width:700px}.checklist,.progress-card{background:')),`overflow-${source}`);expect(result.assertions.responsive).toBe(false)}},90_000);
  it('kills progress loss across locale switching',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`progress-${source}`,(html,key)=>key==='oracle-a'?html.replace('locale.onchange=render','locale.onchange=()=>{checks.forEach(x=>x.checked=false);render()}'):html.replace('code=b.dataset.locale;render()','code=b.dataset.locale;checks.forEach(x=>x.checked=false);render()')),`progress-${source}`);expect(result.assertions.progress_textual_and_persistent).toBe(false)}},90_000);
  it('keeps resolving a native locale select when its accessible label is translated',()=>{const result=evaluate(mutant('oracle-a','localized-select-label',html=>html.replace('document.documentElement.lang=code;',"document.documentElement.lang=code;locale.setAttribute('aria-label',({en:'Choose language',ko:'언어 선택',ja:'言語を選択','zh-CN':'选择语言','zh-TW':'選擇語言'})[code]);")),'localized-select-label');expect(result).toMatchObject({score:100,ui_resolved:true})},90_000);
  it('writes a valid failure score when an optional-state affordance is absent',()=>{const result=evaluate(mutant('oracle-a','missing-unavailable',html=>html.replace('<button id="unavailable">Preview unavailable translation</button>','<span>Unavailable preview is not implemented</span>').replace("document.querySelector('#unavailable').onclick=()=>{document.querySelector('#translation-alert').hidden=false};",'')),'missing-unavailable');expect(result.ui_resolved).toBe(false);expect(result.assertions.translation_unavailable_honest).toBe(false)},90_000);
});
