import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/grant-evidence-intake'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-grant-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','grant-evidence-intake','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-grant-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield grant evidence oracle and mutant calibration',()=>{
  it('accepts board and register implementations',()=>{for(const source of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
  it('kills auto-filled unknowns',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`unknown-${source}`,html=>html.replace(/Unresolved · not provided/g,'$50,000 approved').replace(/Unresolved · not provided/g,'December 2026')),`unknown-${source}`);expect(result.assertions.protected_fields_unresolved).toBe(false)}},60_000);
  it('kills color-only evidence status',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`status-${source}`,html=>html.replace(/<span class="status-label(?: verified| pending| unresolved)?">(?:Verified|Pending|Unresolved)<\/span>/g,'<span class="status-label" aria-label="status">●</span>')),`status-${source}`);expect(result.assertions.every_item_status_textual).toBe(false)}},60_000);
  it('kills a removed unresolved warning',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`warning-${source}`,(html,key)=>key==='oracle-a'?html.replace("warning.hidden=false;document.querySelector('#warning-title')","done.hidden=false;document.querySelector('#submit').hidden=true;document.querySelector('#warning-title')"):html.replace("warning.hidden=false;warning.querySelector('h2')","done.hidden=false;document.querySelector('#submit').hidden=true;warning.querySelector('h2')")),`warning-${source}`);expect(result.assertions.unresolved_warning_before_submit).toBe(false)}},60_000);
});
