import{execFileSync}from'node:child_process';import{cpSync,mkdtempSync,mkdirSync,readFileSync,writeFileSync}from'node:fs';import{join,resolve}from'node:path';import{tmpdir}from'node:os';import{describe,expect,it}from'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/field-notes-editorial'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const d=mkdtempSync(join(tmpdir(),`omd-editorial-${label}-`)),out=join(d,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','field-notes-editorial','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,fn)=>{const w=join(mkdtempSync(join(tmpdir(),`omd-editorial-mutant-${label}-`)),label);mkdirSync(w,{recursive:true});cpSync(join(fixtures,source),w,{recursive:true});const p=join(w,'index.html'),before=readFileSync(p,'utf8'),after=fn(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(p,after);return w};
(enabled?describe:describe.skip)('greenfield editorial oracle and mutant calibration',()=>{
  it('accepts longform-toc and chapter-index implementations',()=>{for(const source of['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
  it('kills a skipped heading rank',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`heading-${source}`,(html,key)=>key==='oracle-a'?html.replace('<h2>Street edges</h2>','<h3>Street edges</h3>'):html.replace('<h2>Rain marks</h2>','<h3>Rain marks</h3>')),`heading-${source}`);expect(result.assertions.heading_outline_valid).toBe(false)}},60_000);
  it('kills conflated caption and citation semantics',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`evidence-${source}`,html=>html.replace(/<cite>([^<]+)<\/cite>/,'<span>$1</span>').replace(/aria-label="(?:Source reference|Citation and source)"/,'aria-label="Editorial note"')),`evidence-${source}`);expect(result.assertions.caption_citation_separate).toBe(false)}},60_000);
  it('kills removed subscription validation',()=>{for(const source of['oracle-a','oracle-b']){const result=evaluate(mutant(source,`validation-${source}`,(html,key)=>key==='oracle-a'?html.replace("const valid=/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email.value)","const valid=true"):html.replace("const ok=/^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$/.test(email.value)","const ok=true")),`validation-${source}`);expect(result.assertions.email_error_associated).toBe(false)}},60_000);
});
