import { execFileSync } from 'node:child_process'; import { cpSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'; import { join, resolve } from 'node:path'; import { tmpdir } from 'node:os'; import { describe, expect, it } from 'vitest';
const enabled=process.env.RUN_UI_RESOLVE_BROWSER_E2E==='1',root=resolve(import.meta.dirname,'../../..'),fixtures=join(root,'benchmarks/ui-resolve-bench/fixtures/autopilot-greenfield/caregiver-onboarding'),evaluator=join(root,'benchmarks/ui-resolve-bench/scripts/evaluate-autopilot-greenfield-task.mjs');
const evaluate=(workspace,label)=>{const dir=mkdtempSync(join(tmpdir(),`omd-care-${label}-`)),out=join(dir,'score.json');execFileSync(process.execPath,[evaluator,'--task-id','caregiver-onboarding','--workspace',workspace,'--out',out],{cwd:root,maxBuffer:4*1024*1024});return JSON.parse(readFileSync(out,'utf8'))};
const mutant=(source,label,transform)=>{const workspace=join(mkdtempSync(join(tmpdir(),`omd-care-mutant-${label}-`)),label);mkdirSync(workspace,{recursive:true});cpSync(join(fixtures,source),workspace,{recursive:true});const path=join(workspace,'index.html'),before=readFileSync(path,'utf8'),after=transform(before,source);if(after===before)throw new Error(`mutant did not alter ${source}`);writeFileSync(path,after);return workspace};
(enabled?describe:describe.skip)('greenfield caregiver oracle and mutant calibration',()=>{
  it('accepts single-card and full-page stepper implementations',()=>{for(const source of ['oracle-a','oracle-b'])expect(evaluate(join(fixtures,source),`valid-${source}`)).toMatchObject({score:100,ui_resolved:true})},60_000);
  it('kills missing current/total progress context',()=>{for(const source of ['oracle-a','oracle-b']){const result=evaluate(mutant(source,`progress-${source}`,html=>html.replace('counter.textContent=`Step ${index+1} of 3`','counter.textContent=`Setup progress`').replace('label.textContent=`Step ${n} of 3 · ${[\'Purpose\',\'Preferences\',\'Review\'][n-1]}`','label.textContent=`Setup progress`')),`progress-${source}`);expect(result.assertions.progress_all_steps).toBe(false)}},60_000);
  it('kills back navigation that loses the selected preference',()=>{for(const source of ['oracle-a','oracle-b']){const result=evaluate(mutant(source,`back-${source}`,(html,kind)=>kind==='oracle-a'?html.replace('back3.onclick=()=>show(2)',"back3.onclick=()=>{document.querySelector('[name=preference]:checked').checked=false;show(2)}"):html.replace("document.querySelector('#review-back').onclick=()=>show(1)","document.querySelector('#review-back').onclick=()=>{document.querySelector('[name=notice]:checked').checked=false;show(1)}")),`back-${source}`);expect(result.assertions.back_preserves_choice).toBe(false)}},60_000);
  it('kills a required-choice validation bypass',()=>{for(const source of ['oracle-a','oracle-b']){const result=evaluate(mutant(source,`validation-${source}`,(html,kind)=>kind==='oracle-a'?html.replace("const choice=document.querySelector('[name=preference]:checked');if(!choice)","const choice=document.querySelector('[name=preference]:checked')||document.querySelector('[name=preference]');if(false)"):html.replace("const picked=document.querySelector('[name=notice]:checked');if(!picked)","const picked=document.querySelector('[name=notice]:checked')||document.querySelector('[name=notice]');if(false)")),`validation-${source}`);expect(result.assertions.empty_choice_blocked).toBe(false)}},60_000);
});
